app_name = "anyadha_pmo"
app_title = "Anyadha PMO"
app_publisher = "Anyadha"
app_description = (
    "Anyadha Enterprise PMO - Governance, Strategy, Programme, Project, "
    "M&E, Grants, CSR, Risk, Compliance, Audit and MIS"
)
app_email = "info@anyadha.com"
app_license = "MIT"
app_version = "2.1.0"

required_apps = ["erpnext"]

after_install = "anyadha_pmo.install.after_install"
after_migrate = "anyadha_pmo.install.after_migrate"

# Frappe v16 application registration.

app_logo_url = "/assets/anyadha_pmo/images/anyadha-pmo-logo.svg"

app_home = "/desk/executive-pmo"

add_to_apps_screen = [
    {
        "name": app_name,
        "logo": app_logo_url,
        "title": app_title,
        "route": app_home,
        "has_permission": "anyadha_pmo.api.app.check_app_permission",
        "sequence_id": 10,
    }
]

# Explicit DocType controller registration.
# Required for reliable DocType discovery/synchronisation on Frappe Cloud.
override_doctype_class = {
    'PMO Access Review': 'anyadha_pmo.risk_internal_controls.doctype.pmo_access_review.pmo_access_review.PmoAccessReview',
    'PMO Action Item': 'anyadha_pmo.project_management.doctype.pmo_action_item.pmo_action_item.PmoActionItem',
    'PMO Approval Request': 'anyadha_pmo.governance.doctype.pmo_approval_request.pmo_approval_request.PmoApprovalRequest',
    'PMO Approval Step': 'anyadha_pmo.governance.doctype.pmo_approval_step.pmo_approval_step.PmoApprovalStep',
    'PMO Asset Assurance': 'anyadha_pmo.risk_internal_controls.doctype.pmo_asset_assurance.pmo_asset_assurance.PmoAssetAssurance',
    'PMO Assurance Review': 'anyadha_pmo.audit_assurance.doctype.pmo_assurance_review.pmo_assurance_review.PmoAssuranceReview',
    'PMO Audit Action': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_action.pmo_audit_action.PmoAuditAction',
    'PMO Audit Area': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_area.pmo_audit_area.PmoAuditArea',
    'PMO Audit Closure': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_closure.pmo_audit_closure.PmoAuditClosure',
    'PMO Audit Engagement': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_engagement.pmo_audit_engagement.PmoAuditEngagement',
    'PMO Audit Finding': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_finding.pmo_audit_finding.PmoAuditFinding',
    'PMO Audit Observation': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_observation.pmo_audit_observation.PmoAuditObservation',
    'PMO Audit Plan': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_plan.pmo_audit_plan.PmoAuditPlan',
    'PMO Audit Recommendation': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_recommendation.pmo_audit_recommendation.PmoAuditRecommendation',
    'PMO Audit Report': 'anyadha_pmo.audit_assurance.doctype.pmo_audit_report.pmo_audit_report.PmoAuditReport',
    'PMO Audit Type': 'anyadha_pmo.pmo_masters.doctype.pmo_audit_type.pmo_audit_type.PmoAuditType',
    'PMO Authority Matrix': 'anyadha_pmo.governance.doctype.pmo_authority_matrix.pmo_authority_matrix.PmoAuthorityMatrix',
    'PMO Authority Rule': 'anyadha_pmo.governance.doctype.pmo_authority_rule.pmo_authority_rule.PmoAuthorityRule',
    'PMO Baseline Indicator': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_baseline_indicator.pmo_baseline_indicator.PmoBaselineIndicator',
    'PMO Baseline Survey': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_baseline_survey.pmo_baseline_survey.PmoBaselineSurvey',
    'PMO Board Agenda Item': 'anyadha_pmo.governance.doctype.pmo_board_agenda_item.pmo_board_agenda_item.PmoBoardAgendaItem',
    'PMO Board Decision': 'anyadha_pmo.governance.doctype.pmo_board_decision.pmo_board_decision.PmoBoardDecision',
    'PMO Board Meeting': 'anyadha_pmo.governance.doctype.pmo_board_meeting.pmo_board_meeting.PmoBoardMeeting',
    'PMO Business Unit': 'anyadha_pmo.pmo_masters.doctype.pmo_business_unit.pmo_business_unit.PmoBusinessUnit',
    'PMO CSR Agreement': 'anyadha_pmo.csr_management.doctype.pmo_csr_agreement.pmo_csr_agreement.PmoCsrAgreement',
    'PMO CSR Budget': 'anyadha_pmo.csr_management.doctype.pmo_csr_budget.pmo_csr_budget.PmoCsrBudget',
    'PMO CSR Compliance': 'anyadha_pmo.csr_management.doctype.pmo_csr_compliance.pmo_csr_compliance.PmoCsrCompliance',
    'PMO CSR Impact Assessment': 'anyadha_pmo.csr_management.doctype.pmo_csr_impact_assessment.pmo_csr_impact_assessment.PmoCsrImpactAssessment',
    'PMO CSR Partner': 'anyadha_pmo.csr_management.doctype.pmo_csr_partner.pmo_csr_partner.PmoCsrPartner',
    'PMO CSR Project': 'anyadha_pmo.csr_management.doctype.pmo_csr_project.pmo_csr_project.PmoCsrProject',
    'PMO CSR Proposal': 'anyadha_pmo.csr_management.doctype.pmo_csr_proposal.pmo_csr_proposal.PmoCsrProposal',
    'PMO CSR Report': 'anyadha_pmo.csr_management.doctype.pmo_csr_report.pmo_csr_report.PmoCsrReport',
    'PMO CSR Utilization': 'anyadha_pmo.csr_management.doctype.pmo_csr_utilization.pmo_csr_utilization.PmoCsrUtilization',
    'PMO Change Request': 'anyadha_pmo.project_management.doctype.pmo_change_request.pmo_change_request.PmoChangeRequest',
    'PMO Compliance Action': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_action.pmo_compliance_action.PmoComplianceAction',
    'PMO Compliance Calendar': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_calendar.pmo_compliance_calendar.PmoComplianceCalendar',
    'PMO Compliance Certificate': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_certificate.pmo_compliance_certificate.PmoComplianceCertificate',
    'PMO Compliance Item': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_item.pmo_compliance_item.PmoComplianceItem',
    'PMO Compliance Obligation': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_obligation.pmo_compliance_obligation.PmoComplianceObligation',
    'PMO Compliance Review': 'anyadha_pmo.compliance_regulatory.doctype.pmo_compliance_review.pmo_compliance_review.PmoComplianceReview',
    'PMO Compliance Type': 'anyadha_pmo.pmo_masters.doctype.pmo_compliance_type.pmo_compliance_type.PmoComplianceType',
    'PMO Contract Governance': 'anyadha_pmo.governance.doctype.pmo_contract_governance.pmo_contract_governance.PmoContractGovernance',
    'PMO Control': 'anyadha_pmo.risk_internal_controls.doctype.pmo_control.pmo_control.PmoControl',
    'PMO Control Self Assessment': 'anyadha_pmo.risk_internal_controls.doctype.pmo_control_self_assessment.pmo_control_self_assessment.PmoControlSelfAssessment',
    'PMO Control Test': 'anyadha_pmo.risk_internal_controls.doctype.pmo_control_test.pmo_control_test.PmoControlTest',
    'PMO Corrective Action': 'anyadha_pmo.risk_internal_controls.doctype.pmo_corrective_action.pmo_corrective_action.PmoCorrectiveAction',
    'PMO DPR': 'anyadha_pmo.proposal_dpr.doctype.pmo_dpr.pmo_dpr.PmoDpr',
    'PMO DPR Approval': 'anyadha_pmo.proposal_dpr.doctype.pmo_dpr_approval.pmo_dpr_approval.PmoDprApproval',
    'PMO DPR Section': 'anyadha_pmo.proposal_dpr.doctype.pmo_dpr_section.pmo_dpr_section.PmoDprSection',
    'PMO Data Governance Rule': 'anyadha_pmo.risk_internal_controls.doctype.pmo_data_governance_rule.pmo_data_governance_rule.PmoDataGovernanceRule',
    'PMO Document Approval': 'anyadha_pmo.sop_document_control.doctype.pmo_document_approval.pmo_document_approval.PmoDocumentApproval',
    'PMO Document Control': 'anyadha_pmo.sop_document_control.doctype.pmo_document_control.pmo_document_control.PmoDocumentControl',
    'PMO Document Review': 'anyadha_pmo.sop_document_control.doctype.pmo_document_review.pmo_document_review.PmoDocumentReview',
    'PMO Document Type': 'anyadha_pmo.pmo_masters.doctype.pmo_document_type.pmo_document_type.PmoDocumentType',
    'PMO Document Version': 'anyadha_pmo.sop_document_control.doctype.pmo_document_version.pmo_document_version.PmoDocumentVersion',
    'PMO Donor': 'anyadha_pmo.pmo_masters.doctype.pmo_donor.pmo_donor.PmoDonor',
    'PMO Donor Compliance': 'anyadha_pmo.grants_donor_management.doctype.pmo_donor_compliance.pmo_donor_compliance.PmoDonorCompliance',
    'PMO Donor Report': 'anyadha_pmo.grants_donor_management.doctype.pmo_donor_report.pmo_donor_report.PmoDonorReport',
    'PMO Enterprise Risk': 'anyadha_pmo.risk_internal_controls.doctype.pmo_enterprise_risk.pmo_enterprise_risk.PmoEnterpriseRisk',
    'PMO Entity': 'anyadha_pmo.pmo_masters.doctype.pmo_entity.pmo_entity.PmoEntity',
    'PMO Evaluation': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_evaluation.pmo_evaluation.PmoEvaluation',
    'PMO Evaluation Finding': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_evaluation_finding.pmo_evaluation_finding.PmoEvaluationFinding',
    'PMO Exception Request': 'anyadha_pmo.governance.doctype.pmo_exception_request.pmo_exception_request.PmoExceptionRequest',
    'PMO Financial Performance Review': 'anyadha_pmo.performance_mis.doctype.pmo_financial_performance_review.pmo_financial_performance_review.PmoFinancialPerformanceReview',
    'PMO Fraud Incident': 'anyadha_pmo.risk_internal_controls.doctype.pmo_fraud_incident.pmo_fraud_incident.PmoFraudIncident',
    'PMO Fraud Risk': 'anyadha_pmo.risk_internal_controls.doctype.pmo_fraud_risk.pmo_fraud_risk.PmoFraudRisk',
    'PMO Fund Reconciliation': 'anyadha_pmo.grants_donor_management.doctype.pmo_fund_reconciliation.pmo_fund_reconciliation.PmoFundReconciliation',
    'PMO Funding Source': 'anyadha_pmo.pmo_masters.doctype.pmo_funding_source.pmo_funding_source.PmoFundingSource',
    'PMO Geographic Area': 'anyadha_pmo.pmo_masters.doctype.pmo_geographic_area.pmo_geographic_area.PmoGeographicArea',
    'PMO Governance Action': 'anyadha_pmo.governance.doctype.pmo_governance_action.pmo_governance_action.PmoGovernanceAction',
    'PMO Governance Body': 'anyadha_pmo.governance.doctype.pmo_governance_body.pmo_governance_body.PmoGovernanceBody',
    'PMO Governance Calendar': 'anyadha_pmo.governance.doctype.pmo_governance_calendar.pmo_governance_calendar.PmoGovernanceCalendar',
    'PMO Governance Compliance Declaration': 'anyadha_pmo.governance.doctype.pmo_governance_compliance_declaration.pmo_governance_compliance_declaration.PmoGovernanceComplianceDeclaration',
    'PMO Governance Improvement': 'anyadha_pmo.sop_document_control.doctype.pmo_governance_improvement.pmo_governance_improvement.PmoGovernanceImprovement',
    'PMO Governance Role': 'anyadha_pmo.governance.doctype.pmo_governance_role.pmo_governance_role.PmoGovernanceRole',
    'PMO Grant': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant.pmo_grant.PmoGrant',
    'PMO Grant Agreement': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant_agreement.pmo_grant_agreement.PmoGrantAgreement',
    'PMO Grant Budget': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant_budget.pmo_grant_budget.PmoGrantBudget',
    'PMO Grant Disbursement': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant_disbursement.pmo_grant_disbursement.PmoGrantDisbursement',
    'PMO Grant Reporting': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant_reporting.pmo_grant_reporting.PmoGrantReporting',
    'PMO Grant Utilization': 'anyadha_pmo.grants_donor_management.doctype.pmo_grant_utilization.pmo_grant_utilization.PmoGrantUtilization',
    'PMO Incident': 'anyadha_pmo.risk_internal_controls.doctype.pmo_incident.pmo_incident.PmoIncident',
    'PMO Indicator': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_indicator.pmo_indicator.PmoIndicator',
    'PMO Indicator Reading': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_indicator_reading.pmo_indicator_reading.PmoIndicatorReading',
    'PMO Indicator Type': 'anyadha_pmo.pmo_masters.doctype.pmo_indicator_type.pmo_indicator_type.PmoIndicatorType',
    'PMO Intervention Type': 'anyadha_pmo.pmo_masters.doctype.pmo_intervention_type.pmo_intervention_type.PmoInterventionType',
    'PMO KCI': 'anyadha_pmo.performance_mis.doctype.pmo_kci.pmo_kci.PmoKci',
    'PMO KPI': 'anyadha_pmo.performance_mis.doctype.pmo_kpi.pmo_kpi.PmoKpi',
    'PMO KPI Dimension Row': 'anyadha_pmo.performance_mis.doctype.pmo_kpi_dimension_row.pmo_kpi_dimension_row.PmoKpiDimensionRow',
    'PMO KPI Reading': 'anyadha_pmo.performance_mis.doctype.pmo_kpi_reading.pmo_kpi_reading.PmoKpiReading',
    'PMO KPI Target': 'anyadha_pmo.performance_mis.doctype.pmo_kpi_target.pmo_kpi_target.PmoKpiTarget',
    'PMO KRI': 'anyadha_pmo.performance_mis.doctype.pmo_kri.pmo_kri.PmoKri',
    'PMO Lessons Learned': 'anyadha_pmo.project_management.doctype.pmo_lessons_learned.pmo_lessons_learned.PmoLessonsLearned',
    'PMO License': 'anyadha_pmo.compliance_regulatory.doctype.pmo_license.pmo_license.PmoLicense',
    'PMO Logical Framework': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_logical_framework.pmo_logical_framework.PmoLogicalFramework',
    'PMO M and E Framework': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_m_and_e_framework.pmo_m_and_e_framework.PMOMandEFramework',
    'PMO MIS Report Definition': 'anyadha_pmo.performance_mis.doctype.pmo_mis_report_definition.pmo_mis_report_definition.PmoMisReportDefinition',
    'PMO MIS Snapshot': 'anyadha_pmo.performance_mis.doctype.pmo_mis_snapshot.pmo_mis_snapshot.PmoMisSnapshot',
    'PMO Management Review': 'anyadha_pmo.performance_mis.doctype.pmo_management_review.pmo_management_review.PmoManagementReview',
    'PMO Master Data Change': 'anyadha_pmo.risk_internal_controls.doctype.pmo_master_data_change.pmo_master_data_change.PmoMasterDataChange',
    'PMO Monitoring Observation': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_monitoring_observation.pmo_monitoring_observation.PmoMonitoringObservation',
    'PMO Monitoring Plan': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_monitoring_plan.pmo_monitoring_plan.PmoMonitoringPlan',
    'PMO Monitoring Visit': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_monitoring_visit.pmo_monitoring_visit.PmoMonitoringVisit',
    'PMO Non Compliance': 'anyadha_pmo.compliance_regulatory.doctype.pmo_non_compliance.pmo_non_compliance.PmoNonCompliance',
    'PMO Opportunity': 'anyadha_pmo.proposal_dpr.doctype.pmo_opportunity.pmo_opportunity.PmoOpportunity',
    'PMO Performance Review': 'anyadha_pmo.performance_mis.doctype.pmo_performance_review.pmo_performance_review.PmoPerformanceReview',
    'PMO Policy': 'anyadha_pmo.sop_document_control.doctype.pmo_policy.pmo_policy.PmoPolicy',
    'PMO Portfolio': 'anyadha_pmo.strategy_portfolio.doctype.pmo_portfolio.pmo_portfolio.PmoPortfolio',
    'PMO Portfolio Project': 'anyadha_pmo.strategy_portfolio.doctype.pmo_portfolio_project.pmo_portfolio_project.PmoPortfolioProject',
    'PMO Portfolio Review': 'anyadha_pmo.strategy_portfolio.doctype.pmo_portfolio_review.pmo_portfolio_review.PmoPortfolioReview',
    'PMO Portfolio Risk': 'anyadha_pmo.strategy_portfolio.doctype.pmo_portfolio_risk.pmo_portfolio_risk.PmoPortfolioRisk',
    'PMO Preventive Action': 'anyadha_pmo.risk_internal_controls.doctype.pmo_preventive_action.pmo_preventive_action.PmoPreventiveAction',
    'PMO Procurement Exception': 'anyadha_pmo.governance.doctype.pmo_procurement_exception.pmo_procurement_exception.PmoProcurementException',
    'PMO Program': 'anyadha_pmo.programme_management.doctype.pmo_program.pmo_program.PmoProgram',
    'PMO Program Project': 'anyadha_pmo.programme_management.doctype.pmo_program_project.pmo_program_project.PmoProgramProject',
    'PMO Program Project Row': 'anyadha_pmo.programme_management.doctype.pmo_program_project_row.pmo_program_project_row.PmoProgramProjectRow',
    'PMO Project': 'anyadha_pmo.project_management.doctype.pmo_project.pmo_project.PmoProject',
    'PMO Project Budget': 'anyadha_pmo.project_management.doctype.pmo_project_budget.pmo_project_budget.PmoProjectBudget',
    'PMO Project Category': 'anyadha_pmo.pmo_masters.doctype.pmo_project_category.pmo_project_category.PmoProjectCategory',
    'PMO Project Closure': 'anyadha_pmo.project_management.doctype.pmo_project_closure.pmo_project_closure.PmoProjectClosure',
    'PMO Project Closure Checklist': 'anyadha_pmo.project_management.doctype.pmo_project_closure_checklist.pmo_project_closure_checklist.PmoProjectClosureChecklist',
    'PMO Project Closure Checklist Row': 'anyadha_pmo.project_management.doctype.pmo_project_closure_checklist_row.pmo_project_closure_checklist_row.PmoProjectClosureChecklistRow',
    'PMO Project Deliverable': 'anyadha_pmo.project_management.doctype.pmo_project_deliverable.pmo_project_deliverable.PmoProjectDeliverable',
    'PMO Project Dependency': 'anyadha_pmo.project_management.doctype.pmo_project_dependency.pmo_project_dependency.PmoProjectDependency',
    'PMO Project Issue': 'anyadha_pmo.project_management.doctype.pmo_project_issue.pmo_project_issue.PmoProjectIssue',
    'PMO Project Milestone': 'anyadha_pmo.project_management.doctype.pmo_project_milestone.pmo_project_milestone.PmoProjectMilestone',
    'PMO Project Phase': 'anyadha_pmo.project_management.doctype.pmo_project_phase.pmo_project_phase.PmoProjectPhase',
    'PMO Project Review': 'anyadha_pmo.project_management.doctype.pmo_project_review.pmo_project_review.PmoProjectReview',
    'PMO Project Team': 'anyadha_pmo.project_management.doctype.pmo_project_team.pmo_project_team.PmoProjectTeam',
    'PMO Project Type': 'anyadha_pmo.pmo_masters.doctype.pmo_project_type.pmo_project_type.PmoProjectType',
    'PMO Proposal': 'anyadha_pmo.proposal_dpr.doctype.pmo_proposal.pmo_proposal.PmoProposal',
    'PMO Proposal Approval': 'anyadha_pmo.proposal_dpr.doctype.pmo_proposal_approval.pmo_proposal_approval.PmoProposalApproval',
    'PMO Proposal Evaluation': 'anyadha_pmo.proposal_dpr.doctype.pmo_proposal_evaluation.pmo_proposal_evaluation.PmoProposalEvaluation',
    'PMO Record Retention Rule': 'anyadha_pmo.sop_document_control.doctype.pmo_record_retention_rule.pmo_record_retention_rule.PmoRecordRetentionRule',
    'PMO Regulatory Filing': 'anyadha_pmo.compliance_regulatory.doctype.pmo_regulatory_filing.pmo_regulatory_filing.PmoRegulatoryFiling',
    'PMO Regulatory Notice': 'anyadha_pmo.compliance_regulatory.doctype.pmo_regulatory_notice.pmo_regulatory_notice.PmoRegulatoryNotice',
    'PMO Related Party Transaction': 'anyadha_pmo.governance.doctype.pmo_related_party_transaction.pmo_related_party_transaction.PmoRelatedPartyTransaction',
    'PMO Reserved Matter': 'anyadha_pmo.governance.doctype.pmo_reserved_matter.pmo_reserved_matter.PmoReservedMatter',
    'PMO Restricted Fund': 'anyadha_pmo.grants_donor_management.doctype.pmo_restricted_fund.pmo_restricted_fund.PmoRestrictedFund',
    'PMO Risk': 'anyadha_pmo.project_management.doctype.pmo_risk.pmo_risk.PmoRisk',
    'PMO Risk Assessment': 'anyadha_pmo.risk_internal_controls.doctype.pmo_risk_assessment.pmo_risk_assessment.PmoRiskAssessment',
    'PMO Risk Category': 'anyadha_pmo.pmo_masters.doctype.pmo_risk_category.pmo_risk_category.PmoRiskCategory',
    'PMO Risk Treatment': 'anyadha_pmo.risk_internal_controls.doctype.pmo_risk_treatment.pmo_risk_treatment.PmoRiskTreatment',
    'PMO SOP': 'anyadha_pmo.sop_document_control.doctype.pmo_sop.pmo_sop.PmoSop',
    'PMO Settings': 'anyadha_pmo.pmo_masters.doctype.pmo_settings.pmo_settings.PMOSettings',
    'PMO Statutory Registration': 'anyadha_pmo.compliance_regulatory.doctype.pmo_statutory_registration.pmo_statutory_registration.PmoStatutoryRegistration',
    'PMO Strategic Initiative': 'anyadha_pmo.strategy_portfolio.doctype.pmo_strategic_initiative.pmo_strategic_initiative.PmoStrategicInitiative',
    'PMO Strategic Objective': 'anyadha_pmo.pmo_masters.doctype.pmo_strategic_objective.pmo_strategic_objective.PmoStrategicObjective',
    'PMO Strategic Plan': 'anyadha_pmo.strategy_portfolio.doctype.pmo_strategic_plan.pmo_strategic_plan.PmoStrategicPlan',
    'PMO System Change Request': 'anyadha_pmo.risk_internal_controls.doctype.pmo_system_change_request.pmo_system_change_request.PmoSystemChangeRequest',
    'PMO Target': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_target.pmo_target.PmoTarget',
    'PMO Theory of Change': 'anyadha_pmo.monitoring_evaluation.doctype.pmo_theory_of_change.pmo_theory_of_change.PmoTheoryOfChange',
    'PMO Utilization Certificate': 'anyadha_pmo.grants_donor_management.doctype.pmo_utilization_certificate.pmo_utilization_certificate.PmoUtilizationCertificate',
    'PMO Vendor Due Diligence': 'anyadha_pmo.governance.doctype.pmo_vendor_due_diligence.pmo_vendor_due_diligence.PmoVendorDueDiligence',
}
